version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'node'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pw123'
      MYSQL_ROOT_PASSWORD: 'pw123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: